# run this with docker-compose run test
services:
  server:
    image: swift-mqtt-dewpoint:latest
    restart: unless-stopped
    env_file: .env

  local:
    container_name: local-server
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    depends_on:
      - mosquitto
    environment:
      - MOSQUITTO_SERVER=mosquitto

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    platform: linux/amd64
    working_dir: /app
    networks:
      - test
    depends_on:
      - mosquitto-test
    environment:
      - MOSQUITTO_SERVER=mosquitto-test
    command: /bin/bash -xc "swift package clean && swift test"

  mosquitto-test:
    image: eclipse-mosquitto
    networks:
      - test
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/certs:/mosquitto/certs

  mosquitto:
    image: eclipse-mosquitto
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/certs:/mosquitto/certs
    ports:
      - "1883:1883"
      - "8883:8883"
      - "8080:8080"
      - "8081:8081"

networks:
  test:
    driver: bridge
    external: false
